CREATE OR REPLACE TRIGGER "NEF1030"."TRG_SSC_TEMPLATES"
BEFORE INSERT OR UPDATE
ON NEF1030.SSC_TEMPLATES
FOR EACH ROW
DECLARE
BEGIN

   IF REGEXP_LIKE(:new.LIBELLE,'NL|nl') THEN
      :new.ID_CODE_LANGUE := 2;
   END IF;
   
END TRG_SSC_TEMPLATES;
/
SHOW ERRORS;