



--SSC_CODE_TI

--Table
CREATE TABLE SSC_CODE_TI
(
  ID_CODE_TI  INTEGER                           NOT NULL,
  NUMERO      INTEGER,
  CODE        VARCHAR2(10 CHAR),
  LIBELLE     VARCHAR2(500 CHAR),
  HISTORIQUE  INTEGER,
  LEGALE      INTEGER
);

--
Commit;
--

--Index
CREATE UNIQUE INDEX SSC_CODE_TI_PK ON SSC_CODE_TI
(ID_CODE_TI);

--
Commit;
--

--Constraint
ALTER TABLE SSC_CODE_TI ADD (
  CONSTRAINT SSC_CODE_TI_PK
  PRIMARY KEY
  (ID_CODE_TI)
  USING INDEX SSC_CODE_TI_PK
  ENABLE VALIDATE);

--
Commit;
--

--SSC_MUTATION_TI_TYPE

--Table
CREATE TABLE SSC_MUTATION_TI_TYPE
(
  ID_MUTATION_TI_TYPE  INTEGER                  NOT NULL,
  CODE                 VARCHAR2(10 CHAR),
  CODE_BCSS            VARCHAR2(10 CHAR),
  LIBELLE              VARCHAR2(100 CHAR),
  LIBELLE_BCSS         VARCHAR2(100 CHAR)
);

--
Commit;
--

--Index
CREATE UNIQUE INDEX SSC_MUTATION_TI_TYPE_PK ON SSC_MUTATION_TI_TYPE
(ID_MUTATION_TI_TYPE);

--
Commit;
--

--Constraint
ALTER TABLE SSC_MUTATION_TI_TYPE ADD (
  CONSTRAINT SSC_MUTATION_TI_TYPE_PK
  PRIMARY KEY
  (ID_MUTATION_TI_TYPE)
  USING INDEX SSC_MUTATION_TI_TYPE_PK
  ENABLE VALIDATE);

--
Commit;
--


--SSC_MUTATION_TI

--Table
CREATE TABLE SSC_MUTATION_TI
(
  ID_MUTATION_TI             INTEGER            NOT NULL,
  NISS                       VARCHAR2(11 CHAR),
  DATE_MUTATION              DATE,
  ID_MUTATION_TI_TYPE        INTEGER,
  ID_CODE_TI                 INTEGER,
  DATE_EDITION               DATE,
  DATE_TRAITEMENT            DATE,
  COMMENTAIRE                CLOB,
  XML_FLUX                   CLOB,
  DATE_INJECTION             DATE,
  DATE_LAST_MODIF            DATE               DEFAULT CURRENT_TIMESTAMP,
  ID_UTILISATEUR_LAST_MODIF  INTEGER,
  SOFTDELETE                 NUMBER(1)          DEFAULT 0
);

--
Commit;
--

--Index
CREATE UNIQUE INDEX SSC_MUTATION_TI_PK ON SSC_MUTATION_TI
(ID_MUTATION_TI);

--
Commit;
--

--Sequence
CREATE SEQUENCE SSC_MUTATION_TI_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

--
Commit;
--

--Trigger
CREATE OR REPLACE TRIGGER SSC_MUTATION_TI_TRG
BEFORE INSERT
ON SSC_MUTATION_TI
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column ID_MUTATION_TI
  :new.ID_MUTATION_TI := SSC_MUTATION_TI_SEQ.nextval;
END SSC_MUTATION_TI_TRG;
/

--
Commit;
--

--Constraint
ALTER TABLE SSC_MUTATION_TI ADD (
  CONSTRAINT SSC_MUTATION_TI_PK
  PRIMARY KEY
  (ID_MUTATION_TI)
  USING INDEX SSC_MUTATION_TI_PK
  ENABLE VALIDATE);

--
Commit;
--